$(function () {
	$("#filterCollapse").on('show.bs.collapse', function () {
		$("#filterToggler").css("color", "#4F4F4F");
	});
	$('#filterCollapse').on('hidden.bs.collapse', function () {
		$("#filterToggler").css("color", "#A9A9A9");
	});
	$("#searchButton").click(function (event) {
		var sb = $("#searchButton");
		var si = $("#searchInput");
		if (!si.hasClass("inputTransition")) {
			sb.css("color", "#4F4F4F");
			si.addClass("inputTransition");
		} else {
			sb.attr("type", "submit");
		}
		event.stopPropagation();
	});
	$("#headNavbar").click(function(){
		$("#searchInput").removeClass("inputTransition");
		$("#searchButton").css("color", "#A9A9A9");
	});
	$("#searchInput").click(function (event) {
		event.stopPropagation();
	});
	$("#sidebarToggler").click(function () {
		var ss = $("#settingSidebar");
		if (!ss.hasClass("sidebarTransition")) {
			ss.addClass("sidebarTransition");
		} else {
			ss.removeClass("sidebarTransition");
		}
	});
});

new Vue({
	el: '#headNavbar',
	data: {
		tags: [
		{ tag: '剧情' },
		{ tag: '惊悚' },
		{ tag: '冒险' },
		{ tag: '科幻' },
		{ tag: '恐怖' },
		{ tag: '动作' },
		{ tag: '喜剧' },
		{ tag: '灾难' },
		{ tag: '悬疑' },
		]
	}
});

new Vue({
	el: '#filmList',
	data: {
		films: [
		{
			id: 1,
			doubanUrl: 'https://movie.douban.com/subject/1294941/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1108567104.webp',
			score: '7.7',
			filmId: 'Jaws',
			translateName: '大白鲨',
			year: '1975',
			noSeries: false,
			series: [
			{
				seriesId: 'Jaws',
				seriesName: '大白鲨',
				seriesYear: '1975',
			},
			{
				seriesId: 'Jaws2',
				seriesName: '大白鲨2',
				seriesYear: '1978',
			},
			{
				seriesId: 'Jaws3D',
				seriesName: '大白鲨3',
				seriesYear: '1983',
			},
			{
				seriesId: 'JawsTheRevenge',
				seriesName: '大白鲨大报复',
				seriesYear: '1987',
			},
			],
			officialName: 'Jaws',
			country: '美国',
			type: '剧情 / 惊悚 / 冒险',
			director: '史蒂文·斯皮尔伯格',
			star: '罗伊·沙伊德尔 / 罗伯特·肖',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/x0011vrknod.html',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XMzAxNTg5MDA3Ng==.html?spm=a2h0k.11417342.soresults.dposter',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrhxym4w.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 2,
			doubanUrl: 'https://movie.douban.com/subject/1297242/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1108658455.webp',
			score: '6.4',
			filmId: 'Jaws2',
			translateName: '大白鲨2',
			year: '1978',
			noSeries: false,
			series: [
			{
				seriesId: 'Jaws',
				seriesName: '大白鲨',
				seriesYear: '1975',
			},
			{
				seriesId: 'Jaws2',
				seriesName: '大白鲨2',
				seriesYear: '1978',
			},
			{
				seriesId: 'Jaws3D',
				seriesName: '大白鲨3',
				seriesYear: '1983',
			},
			{
				seriesId: 'JawsTheRevenge',
				seriesName: '大白鲨大报复',
				seriesYear: '1987',
			},
			],
			officialName: 'Jaws 2',
			country: '美国',
			type: '惊悚',
			director: '吉诺特·兹瓦克',
			star: '罗伊·沙伊德尔 / 洛兰·加里',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/m0027utkj3x.html',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XMzAxNTg5MDA2NA==.html?spm=a2h0k.11417342.soresults.dposter',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rr8w1a20.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 3,
			doubanUrl: 'https://movie.douban.com/subject/1300868/',
			imgUrl: 'https://img1.doubanio.com/view/photo/m/public/p1756402567.webp',
			score: '8.1',
			filmId: 'Alien',
			translateName: '异形',
			year: '1979',
			noSeries: false,
			series: [
			{
				seriesId: 'Alien',
				seriesName: '异形',
				seriesYear: '1979',
			},
			{
				seriesId: 'Aliens',
				seriesName: '异形2',
				seriesYear: '1986',
			},
			{
				seriesId: 'Alien³',
				seriesName: '异形3',
				seriesYear: '1992',
			},
			{
				seriesId: 'AlienResurrection',
				seriesName: '异形4',
				seriesYear: '1997',
			},
			{
				seriesId: 'Prometheus',
				seriesName: '普罗米修斯',
				seriesYear: '2012',
			},
			{
				seriesId: 'AlienCovenant',
				seriesName: '异形：契约',
				seriesYear: '2017',
			},
			],
			officialName: 'Alien',
			country: '英国 / 美国',
			type: '科幻 / 恐怖',
			director: '雷德利·斯科特',
			star: '西格妮·韦弗 / 汤姆·斯凯里特',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/p0020mgmuki.html',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrk0w4qk.html',
			noOther: false,
			otherUrl: 'https://www.wasu.cn/play/show/id/9665961',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 4,
			doubanUrl: 'https://movie.douban.com/subject/1303765/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1108691070.webp',
			score: '5.8',
			filmId: 'Jaws3D',
			translateName: '大白鲨3',
			year: '1983',
			noSeries: false,
			series: [
			{
				seriesId: 'Jaws',
				seriesName: '大白鲨',
				seriesYear: '1975',
			},
			{
				seriesId: 'Jaws2',
				seriesName: '大白鲨2',
				seriesYear: '1978',
			},
			{
				seriesId: 'Jaws3D',
				seriesName: '大白鲨3',
				seriesYear: '1983',
			},
			{
				seriesId: 'JawsTheRevenge',
				seriesName: '大白鲨大报复',
				seriesYear: '1987',
			},
			],
			officialName: 'Jaws 3-D',
			country: '美国',
			type: '惊悚',
			director: '乔·阿尔夫斯',
			star: '丹尼斯·奎德 / 贝丝·阿姆斯特朗',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/r00208xzgcs.html',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XMTgyMzE0OTAyMA==.html?spm=a2h0k.11417342.soresults.dposter',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrhx3mes.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 5,
			doubanUrl: 'https://movie.douban.com/subject/1293792/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p2493207032.webp',
			score: '8.0',
			filmId: 'Aliens',
			translateName: '异形2',
			year: '1986',
			noSeries: false,
			series: [
			{
				seriesId: 'Alien',
				seriesName: '异形',
				seriesYear: '1979',
			},
			{
				seriesId: 'Aliens',
				seriesName: '异形2',
				seriesYear: '1986',
			},
			{
				seriesId: 'Alien³',
				seriesName: '异形3',
				seriesYear: '1992',
			},
			{
				seriesId: 'AlienResurrection',
				seriesName: '异形4',
				seriesYear: '1997',
			},
			{
				seriesId: 'Prometheus',
				seriesName: '普罗米修斯',
				seriesYear: '2012',
			},
			{
				seriesId: 'AlienCovenant',
				seriesName: '异形：契约',
				seriesYear: '2017',
			},
			],
			officialName: 'Aliens',
			country: '美国 / 英国',
			type: '动作 / 科幻 / 恐怖',
			director: '詹姆斯·卡梅隆',
			star: '西格妮·韦弗 / 凯莉·赫恩',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/k0024z2sfx4.html',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrk0w1l4.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 6,
			doubanUrl: 'https://movie.douban.com/subject/1301844/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p2370610915.webp',
			score: '5.6',
			filmId: 'JawsTheRevenge',
			translateName: '大白鲨大报复',
			year: '1987',
			noSeries: false,
			series: [
			{
				seriesId: 'Jaws',
				seriesName: '大白鲨',
				seriesYear: '1975',
			},
			{
				seriesId: 'Jaws2',
				seriesName: '大白鲨2',
				seriesYear: '1978',
			},
			{
				seriesId: 'Jaws3D',
				seriesName: '大白鲨3',
				seriesYear: '1983',
			},
			{
				seriesId: 'JawsTheRevenge',
				seriesName: '大白鲨大报复',
				seriesYear: '1987',
			},
			],
			officialName: 'Jaws: The Revenge',
			country: '美国',
			type: '惊悚',
			director: '约瑟夫·萨金特',
			star: '洛兰·加里 / 兰斯·盖斯特',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XMzUwNjQ5MjIyOA==.html?spm=a2h0k.11417342.soresults.dposter',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrhx8tzk.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 7,
			doubanUrl: 'https://movie.douban.com/subject/1297929/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p2408593936.webp',
			score: '7.1',
			filmId: 'Alien³',
			translateName: '异形3',
			year: '1992',
			noSeries: false,
			series: [
			{
				seriesId: 'Alien',
				seriesName: '异形',
				seriesYear: '1979',
			},
			{
				seriesId: 'Aliens',
				seriesName: '异形2',
				seriesYear: '1986',
			},
			{
				seriesId: 'Alien³',
				seriesName: '异形3',
				seriesYear: '1992',
			},
			{
				seriesId: 'AlienResurrection',
				seriesName: '异形4',
				seriesYear: '1997',
			},
			{
				seriesId: 'Prometheus',
				seriesName: '普罗米修斯',
				seriesYear: '2012',
			},
			{
				seriesId: 'AlienCovenant',
				seriesName: '异形：契约',
				seriesYear: '2017',
			},
			],
			officialName: 'Alien³',
			country: '美国',
			type: '动作 / 科幻 / 恐怖',
			director: '大卫·芬奇',
			star: '西格妮·韦弗 / 查尔斯·达顿',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/n00204bfdnp.html',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrk16mu0.html',
			noOther: false,
			otherUrl: 'https://www.wasu.cn/play/show/id/9649815',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 8,
			doubanUrl: 'https://movie.douban.com/subject/1299153/',
			imgUrl: 'https://img1.doubanio.com/view/photo/m/public/p1101480167.webp',
			score: '7.6',
			filmId: 'AlienResurrection',
			translateName: '异形4',
			year: '1997',
			noSeries: false,
			series: [
			{
				seriesId: 'Alien',
				seriesName: '异形',
				seriesYear: '1979',
			},
			{
				seriesId: 'Aliens',
				seriesName: '异形2',
				seriesYear: '1986',
			},
			{
				seriesId: 'Alien³',
				seriesName: '异形3',
				seriesYear: '1992',
			},
			{
				seriesId: 'AlienResurrection',
				seriesName: '异形4',
				seriesYear: '1997',
			},
			{
				seriesId: 'Prometheus',
				seriesName: '普罗米修斯',
				seriesYear: '2012',
			},
			{
				seriesId: 'AlienCovenant',
				seriesName: '异形：契约',
				seriesYear: '2017',
			},
			],
			officialName: 'Alien: Resurrection',
			country: '美国',
			type: '动作 / 科幻 / 恐怖',
			director: '让-皮埃尔·热内',
			star: '西格妮·韦弗 / 薇诺娜·瑞德',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/h0020wolxu4.html',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrk176sk.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 9,
			doubanUrl: 'https://movie.douban.com/subject/1294276/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1860661551.webp',
			score: '6.4',
			filmId: 'Mimic',
			translateName: '变种DNA',
			year: '1997',
			noSeries: false,
			series: [
			{
				seriesId: 'Mimic',
				seriesName: '变种DNA',
				seriesYear: '1997',
			},
			{
				seriesId: 'Mimic2',
				seriesName: '变种DNA 2',
				seriesYear: '2001',
			},
			{
				seriesId: 'MimicSentinel',
				seriesName: '变种DNA 3：哨兵',
				seriesYear: '2003',
			},
			],
			officialName: 'Mimic',
			country: '美国',
			type: '剧情 / 科幻 / 恐怖',
			director: '吉尔莫·德尔·托罗',
			star: '米拉·索维诺 / 杰瑞米·诺森',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/p0022ju0a3r.html',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrjr6dn8.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 10,
			doubanUrl: 'https://movie.douban.com/subject/1422986/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1242457462.webp',
			score: '5.7',
			filmId: 'Mimic2',
			translateName: '变种DNA 2',
			year: '2001',
			noSeries: false,
			series: [
			{
				seriesId: 'Mimic',
				seriesName: '变种DNA',
				seriesYear: '1997',
			},
			{
				seriesId: 'Mimic2',
				seriesName: '变种DNA 2',
				seriesYear: '2001',
			},
			{
				seriesId: 'MimicSentinel',
				seriesName: '变种DNA 3：哨兵',
				seriesYear: '2003',
			},
			],
			officialName: 'Mimic 2',
			country: '美国',
			type: '科幻 / 惊悚 / 恐怖',
			director: '让·德·塞贡扎克',
			star: '阿里克斯·库拉姆乔伊 / 布鲁诺·坎波斯',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/b00249nywfh.html',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrjr69a0.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 11,
			doubanUrl: 'https://movie.douban.com/subject/1422987/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1242465793.webp',
			score: '4.6',
			filmId: 'MimicSentinel',
			translateName: '变种DNA 3：哨兵',
			year: '2003',
			noSeries: false,
			series: [
			{
				seriesId: 'Mimic',
				seriesName: '变种DNA',
				seriesYear: '1997',
			},
			{
				seriesId: 'Mimic2',
				seriesName: '变种DNA 2',
				seriesYear: '2001',
			},
			{
				seriesId: 'MimicSentinel',
				seriesName: '变种DNA 3：哨兵',
				seriesYear: '2003',
			},
			],
			officialName: 'Mimic: Sentinel',
			country: '美国',
			type: '科幻 / 惊悚 / 恐怖',
			director: 'J.T. Petty',
			star: 'Karl Geary / 约翰.卡普洛斯',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/i0024x7pglg.html',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrjr8ywo.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 12,
			doubanUrl: 'https://movie.douban.com/subject/1309088/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p2254829302.webp',
			score: '7.5',
			filmId: 'DawnoftheDead',
			translateName: '活死人黎明',
			year: '2004',
			noSeries: false,
			series: [
			{
				seriesId: 'DawnoftheDead',
				seriesName: '活死人黎明',
				seriesYear: '2004',
			},
			{
				seriesId: 'LandoftheDead',
				seriesName: '活死人之地',
				seriesYear: '2005',
			},
			{
				seriesId: 'NightoftheLivingDead3D',
				seriesName: '新活死人之夜',
				seriesYear: '2006',
			},
			{
				seriesId: 'DiaryoftheDead',
				seriesName: '死亡日记',
				seriesYear: '2007',
			},
			{
				seriesId: 'DayoftheDead',
				seriesName: '新丧尸出笼',
				seriesYear: '2008',
			},
			{
				seriesId: 'SurvivaloftheDead',
				seriesName: '死人岛',
				seriesYear: '2009',
			},
			],
			officialName: 'Dawn of the Dead',
			country: '美国 / 加拿大 / 日本 / 法国',
			type: '动作 / 科幻 / 恐怖',
			director: '扎克·施奈德',
			star: '萨拉·波莉 / 文·瑞姆斯',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/o0024x0526f.html',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 13,
			doubanUrl: 'https://movie.douban.com/subject/1308755/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1109815924.webp',
			score: '7.7',
			filmId: 'ShaunoftheDead',
			translateName: '僵尸肖恩',
			year: '2004',
			noSeries: false,
			series: [
			{
				seriesId: 'ShaunoftheDead',
				seriesName: '僵尸肖恩',
				seriesYear: '2004',
			},
			{
				seriesId: 'HotFuzz',
				seriesName: '热血警探',
				seriesYear: '2007',
			},
			{
				seriesId: 'TheWorldsEnd',
				seriesName: '世界尽头',
				seriesYear: '2013',
			},
			],
			officialName: 'Shaun of the Dead',
			country: '英国 / 法国 / 美国',
			type: '喜剧 / 恐怖',
			director: '埃德加·赖特',
			star: '西蒙·佩吉 / 尼克·弗罗斯特',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: true,
			otherUrl: '',
			noDownload: false,
			downloadUrl: 'https://pan.baidu.com/s/1jSNOV2LLjEOojbyagipPsg',
		},
		{
			id: 14,
			doubanUrl: 'https://baike.baidu.com/item/%E6%B4%BB%E6%AD%BB%E4%BA%BA%E4%B9%8B%E5%9C%B0/35692',
			imgUrl: 'https://gss3.bdstatic.com/-Po3dSag_xI4khGkpoWK1HF6hhy/baike/c0%3Dbaike80%2C5%2C5%2C80%2C26/sign=eadee08cb5fd5266b3263446ca71fc4e/f31fbe096b63f6240075d5648444ebf81a4ca3a9.jpg',
			score: '6.4',
			filmId: 'LandoftheDead',
			translateName: '活死人之地',
			year: '2005',
			noSeries: false,
			series: [
			{
				seriesId: 'DawnoftheDead',
				seriesName: '活死人黎明',
				seriesYear: '2004',
			},
			{
				seriesId: 'LandoftheDead',
				seriesName: '活死人之地',
				seriesYear: '2005',
			},
			{
				seriesId: 'NightoftheLivingDead3D',
				seriesName: '新活死人之夜',
				seriesYear: '2006',
			},
			{
				seriesId: 'DiaryoftheDead',
				seriesName: '死亡日记',
				seriesYear: '2007',
			},
			{
				seriesId: 'DayoftheDead',
				seriesName: '新丧尸出笼',
				seriesYear: '2008',
			},
			{
				seriesId: 'SurvivaloftheDead',
				seriesName: '死人岛',
				seriesYear: '2009',
			},
			],
			officialName: 'Land of the Dead',
			country: '美国 / 法国 / 加拿大',
			type: '动作',
			director: '乔治·A·罗梅罗',
			star: '西蒙·贝克尔 / 丹尼斯·霍珀',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: false,
			otherUrl: 'https://www.halihali.tv/v/hsrzd/0-1.html',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 15,
			doubanUrl: 'https://movie.douban.com/subject/1309044/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p2181492306.webp',
			score: '6.5',
			filmId: 'WaroftheWorlds',
			translateName: '世界之战',
			year: '2005',
			noSeries: true,
			series: [
			{
				seriesId: '',
				seriesName: '',
				seriesYear: '',
			},
			],
			officialName: 'War of the Worlds',
			country: '美国',
			type: '科幻 / 惊悚 / 灾难',
			director: '史蒂文·斯皮尔伯格',
			star: '汤姆·克鲁斯 / 达科塔·范宁',
			note: '外星人入侵 屠杀 末日 逃生 人性 血腥',
			noBilibili: false,
			bilibiliUrl: 'https://www.bilibili.com/bangumi/play/ss25508/',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/l0018tobe9v.html',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XMTMzNTU0OTAyMA==.html?spm=a2h0k.11417342.soresults.dplaybutton&lang=%E8%8B%B1%E8%AF%AD',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrnppkc8.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 16,
			doubanUrl: 'https://movie.douban.com/subject/1839849/',
			imgUrl: 'https://img1.doubanio.com/view/subject/l/public/s1693427.jpg',
			score: '4.7',
			filmId: 'NightoftheLivingDead3D',
			translateName: '新活死人之夜',
			year: '2006',
			noSeries: false,
			series: [
			{
				seriesId: 'DawnoftheDead',
				seriesName: '活死人黎明',
				seriesYear: '2004',
			},
			{
				seriesId: 'LandoftheDead',
				seriesName: '活死人之地',
				seriesYear: '2005',
			},
			{
				seriesId: 'NightoftheLivingDead3D',
				seriesName: '新活死人之夜',
				seriesYear: '2006',
			},
			{
				seriesId: 'DiaryoftheDead',
				seriesName: '死亡日记',
				seriesYear: '2007',
			},
			{
				seriesId: 'DayoftheDead',
				seriesName: '新丧尸出笼',
				seriesYear: '2008',
			},
			{
				seriesId: 'SurvivaloftheDead',
				seriesName: '死人岛',
				seriesYear: '2009',
			},
			],
			officialName: 'Night of the Living Dead 3D',
			country: '美国',
			type: '喜剧 / 科幻 / 恐怖 / 冒险',
			director: '杰夫·布罗德史崔特',
			star: '布兰娜·布朗 / Sid Haig',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: true,
			otherUrl: '',
			noDownload: false,
			downloadUrl: 'https://www.baidu.com/s?wd=%E6%96%B0%E6%B4%BB%E6%AD%BB%E4%BA%BA%E4%B9%8B%E5%A4%9C%20%E4%B8%8B%E8%BD%BD&rsv_spt=1&rsv_iqid=0xddfb996b0009458a&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&rqlang=cn&tn=baiduhome_pg&rsv_enter=0&oq=%25E6%2596%25B0%25E6%25B4%25BB%25E6%25AD%25BB%25E4%25BA%25BA%25E4%25B9%258B%25E5%25A4%259C%2520%25E4%25B8%258B%25E8%25BD%25BD&rsv_t=94aa8OXDogCMZaFb2ocBSNHX08Kj%2BFC8htvXnytPMXunvbuHSTp8sAT2%2B8rbva1r2jAK&rsv_pq=c62764a40009691d',
		},
		{
			id: 17,
			doubanUrl: 'https://movie.douban.com/subject/1806555/',
			imgUrl: 'https://img1.doubanio.com/view/photo/m/public/p1774982769.webp',
			score: '8.3',
			filmId: 'HotFuzz',
			translateName: '热血警探',
			year: '2007',
			noSeries: false,
			series: [
			{
				seriesId: 'ShaunoftheDead',
				seriesName: '僵尸肖恩',
				seriesYear: '2004',
			},
			{
				seriesId: 'HotFuzz',
				seriesName: '热血警探',
				seriesYear: '2007',
			},
			{
				seriesId: 'TheWorldsEnd',
				seriesName: '世界尽头',
				seriesYear: '2013',
			},
			],
			officialName: 'Hot Fuzz',
			country: '美国 / 法国 / 英国',
			type: '喜剧 / 动作',
			director: '埃德加·赖特',
			star: '西蒙·佩吉 / 尼克·弗罗斯特',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/s0013a80wxq.html',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XNzM0NjUzMDky.html?spm=a2h0k.11417342.soresults.dplaybutton&s=cc0d3f60962411de83b1',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrhwqabs.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 18,
			doubanUrl: 'https://movie.douban.com/subject/1865656/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p2053952350.webp',
			score: '5.8',
			filmId: 'DiaryoftheDead',
			translateName: '死亡日记',
			year: '2007',
			noSeries: false,
			series: [
			{
				seriesId: 'DawnoftheDead',
				seriesName: '活死人黎明',
				seriesYear: '2004',
			},
			{
				seriesId: 'LandoftheDead',
				seriesName: '活死人之地',
				seriesYear: '2005',
			},
			{
				seriesId: 'NightoftheLivingDead3D',
				seriesName: '新活死人之夜',
				seriesYear: '2006',
			},
			{
				seriesId: 'DiaryoftheDead',
				seriesName: '死亡日记',
				seriesYear: '2007',
			},
			{
				seriesId: 'DayoftheDead',
				seriesName: '新丧尸出笼',
				seriesYear: '2008',
			},
			{
				seriesId: 'SurvivaloftheDead',
				seriesName: '死人岛',
				seriesYear: '2009',
			},
			],
			officialName: 'Diary of the Dead',
			country: '美国',
			type: '科幻 / 恐怖',
			director: '乔治·A·罗梅罗',
			star: '肖恩·罗伯茨 / 梅根·帕克',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: true,
			otherUrl: '',
			noDownload: false,
			downloadUrl: 'https://pan.baidu.com/s/1JY0J7aen2dptSTa_zG2GRg',
		},
		{
			id: 19,
			doubanUrl: 'https://movie.douban.com/subject/1871840/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1439880843.webp',
			score: '6.4',
			filmId: 'DayoftheDead',
			translateName: '新丧尸出笼',
			year: '2008',
			noSeries: false,
			series: [
			{
				seriesId: 'DawnoftheDead',
				seriesName: '活死人黎明',
				seriesYear: '2004',
			},
			{
				seriesId: 'LandoftheDead',
				seriesName: '活死人之地',
				seriesYear: '2005',
			},
			{
				seriesId: 'NightoftheLivingDead3D',
				seriesName: '新活死人之夜',
				seriesYear: '2006',
			},
			{
				seriesId: 'DiaryoftheDead',
				seriesName: '死亡日记',
				seriesYear: '2007',
			},
			{
				seriesId: 'DayoftheDead',
				seriesName: '新丧尸出笼',
				seriesYear: '2008',
			},
			{
				seriesId: 'SurvivaloftheDead',
				seriesName: '死人岛',
				seriesYear: '2009',
			},
			],
			officialName: 'Day of the Dead',
			country: '美国',
			type: '惊悚 / 恐怖',
			director: '史蒂夫·迈纳',
			star: '米娜·苏瓦丽 / 尼克·卡农',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XMjgxNzg3NDg5Mg==.html',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 20,
			doubanUrl: 'https://movie.douban.com/subject/2144242/',
			imgUrl: 'https://img1.doubanio.com/view/photo/m/public/p1334135449.webp',
			score: '7.3',
			filmId: 'Cloverfield',
			translateName: '科洛弗档案',
			year: '2008',
			noSeries: false,
			series: [
			{
				seriesId: 'Cloverfield',
				seriesName: '科洛弗档案',
				seriesYear: '2008',
			},
			{
				seriesId: '10CloverfieldLane',
				seriesName: '科洛弗道10号',
				seriesYear: '2016',
			},
			{
				seriesId: 'TheCloverfieldParadox',
				seriesName: '科洛弗悖论',
				seriesYear: '2018',
			},
			],
			officialName: 'Cloverfield',
			country: '美国',
			type: '科幻 / 惊悚 / 灾难',
			director: '马特·里夫斯',
			star: '丽兹·卡潘 / 杰西卡·卢卡斯',
			note: '外星人入侵 屠杀 末日 逃生 人性 血腥',
			noBilibili: false,
			bilibiliUrl: 'https://www.bilibili.com/bangumi/play/ss25914/',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/r0021y9cvf0.html',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XMTMyMDQ3NzI0OA==.html?spm=a2h0k.11417342.soresults.dplaybutton&s=cc0e8e88962411de83b1',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrgcwam0.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 21,
			doubanUrl: 'https://baike.baidu.com/item/%E6%AD%BB%E4%BA%BA%E5%B2%9B/10241901',
			imgUrl: 'https://gss0.bdstatic.com/94o3dSag_xI4khGkpoWK1HF6hhy/baike/c0%3Dbaike272%2C5%2C5%2C272%2C90/sign=0b6dd7d4f1039245b5b8e95de6fdcfa7/0eb30f2442a7d9330036c56aa04bd11373f00108.jpg',
			score: '4.6',
			filmId: 'SurvivaloftheDead',
			translateName: '死人岛',
			year: '2009',
			noSeries: false,
			series: [
			{
				seriesId: 'DawnoftheDead',
				seriesName: '活死人黎明',
				seriesYear: '2004',
			},
			{
				seriesId: 'LandoftheDead',
				seriesName: '活死人之地',
				seriesYear: '2005',
			},
			{
				seriesId: 'NightoftheLivingDead3D',
				seriesName: '新活死人之夜',
				seriesYear: '2006',
			},
			{
				seriesId: 'DiaryoftheDead',
				seriesName: '死亡日记',
				seriesYear: '2007',
			},
			{
				seriesId: 'DayoftheDead',
				seriesName: '新丧尸出笼',
				seriesYear: '2008',
			},
			{
				seriesId: 'SurvivaloftheDead',
				seriesName: '死人岛',
				seriesYear: '2009',
			},
			],
			officialName: 'Survival of the Dead',
			country: '美国 / 加拿大',
			type: '恐怖',
			director: '乔治·A·罗梅罗',
			star: '戴文·博斯蒂克 / Alan Van Sprang',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: false,
			otherUrl: 'https://www.halihali.tv/v/srd/0-1.html',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 22,
			doubanUrl: 'https://movie.douban.com/subject/3771562/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1548920463.webp',
			score: '7.3',
			filmId: 'Prometheus',
			translateName: '普罗米修斯',
			year: '2012',
			noSeries: false,
			series: [
			{
				seriesId: 'Alien',
				seriesName: '异形',
				seriesYear: '1979',
			},
			{
				seriesId: 'Aliens',
				seriesName: '异形2',
				seriesYear: '1986',
			},
			{
				seriesId: 'Alien³',
				seriesName: '异形3',
				seriesYear: '1992',
			},
			{
				seriesId: 'AlienResurrection',
				seriesName: '异形4',
				seriesYear: '1997',
			},
			{
				seriesId: 'Prometheus',
				seriesName: '普罗米修斯',
				seriesYear: '2012',
			},
			{
				seriesId: 'AlienCovenant',
				seriesName: '异形：契约',
				seriesYear: '2017',
			},
			],
			officialName: 'Prometheus',
			country: '美国 / 英国',
			type: '科幻 / 惊悚 / 冒险',
			director: '雷德利·斯科特',
			star: '劳米·拉佩斯 / 迈克尔·法斯宾德',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/x0020qpyeen.html',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rrhoa87s.html',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 23,
			doubanUrl: 'https://movie.douban.com/subject/3026572/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p1955267614.webp',
			score: '7.4',
			filmId: 'TheWorldsEnd',
			translateName: '世界尽头',
			year: '2013',
			noSeries: false,
			series: [
			{
				seriesId: 'ShaunoftheDead',
				seriesName: '僵尸肖恩',
				seriesYear: '2004',
			},
			{
				seriesId: 'HotFuzz',
				seriesName: '热血警探',
				seriesYear: '2007',
			},
			{
				seriesId: 'TheWorldsEnd',
				seriesName: '世界尽头',
				seriesYear: '2013',
			},
			],
			officialName: 'The World\'s End',
			country: '英国',
			type: '喜剧 / 动作 / 科幻',
			director: '埃德加·赖特',
			star: '西蒙·佩吉 / 尼克·弗罗斯特',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XMzA5MzA2MDMyOA==.html?spm=a2h0k.11417342.soresults.dplaybutton&s=cc1265f8962411de83b1',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 24,
			doubanUrl: 'https://movie.douban.com/subject/2977957/',
			imgUrl: 'https://img1.doubanio.com/view/photo/m/public/p2310097289.webp',
			score: '6.8',
			filmId: '10CloverfieldLane',
			translateName: '科洛弗道10号',
			year: '2016',
			noSeries: false,
			series: [
			{
				seriesId: 'Cloverfield',
				seriesName: '科洛弗档案',
				seriesYear: '2008',
			},
			{
				seriesId: '10CloverfieldLane',
				seriesName: '科洛弗道10号',
				seriesYear: '2016',
			},
			{
				seriesId: 'TheCloverfieldParadox',
				seriesName: '科洛弗悖论',
				seriesYear: '2018',
			},
			],
			officialName: '10 Cloverfield Lane',
			country: '美国',
			type: '科幻 / 悬疑 / 惊悚',
			director: '丹·特拉亨伯格',
			star: '约翰·古德曼 / 玛丽·伊丽莎白·温斯特德',
			note: '外星人入侵 屠杀 末日 逃生 人性 血腥',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: false,
			tencentUrl: 'https://v.qq.com/x/page/h0020w2sj5p.html',
			noYouku: false,
			youkuUrl: 'https://v.youku.com/v_show/id_XMTY5ODkyNTk4MA==.html?spm=a2h0k.11417342.soresults.dplaybutton&s=4b884c90b58611df97c0',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: true,
			otherUrl: '',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 25,
			doubanUrl: 'https://movie.douban.com/subject/11803087/',
			imgUrl: 'https://img3.doubanio.com/view/photo/m/public/p2458710053.webp',
			score: '7.4',
			filmId: 'AlienCovenant',
			translateName: '异形：契约',
			year: '2017',
			noSeries: false,
			series: [
			{
				seriesId: 'Alien',
				seriesName: '异形',
				seriesYear: '1979',
			},
			{
				seriesId: 'Aliens',
				seriesName: '异形2',
				seriesYear: '1986',
			},
			{
				seriesId: 'Alien³',
				seriesName: '异形3',
				seriesYear: '1992',
			},
			{
				seriesId: 'AlienResurrection',
				seriesName: '异形4',
				seriesYear: '1997',
			},
			{
				seriesId: 'Prometheus',
				seriesName: '普罗米修斯',
				seriesYear: '2012',
			},
			{
				seriesId: 'AlienCovenant',
				seriesName: '异形：契约',
				seriesYear: '2017',
			},
			],
			officialName: 'Alien: Covenant',
			country: '美国',
			type: '科幻 / 恐怖',
			director: '雷德利·斯科特',
			star: '迈克尔·法斯宾德 / 凯瑟琳·沃特斯顿',
			note: '经典大白鲨系列~',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: false,
			iqiyiUrl: 'http://www.iqiyi.com/v_19rr9sidfk.html',
			noOther: false,
			otherUrl: 'https://www.wasu.cn/play/show/id/9665764',
			noDownload: true,
			downloadUrl: '',
		},
		{
			id: 26,
			doubanUrl: 'https://movie.douban.com/subject/21328095/',
			imgUrl: 'https://img1.doubanio.com/view/photo/m/public/p2512711499.webp',
			score: '6.0',
			filmId: 'TheCloverfieldParadox',
			translateName: '科洛弗悖论',
			year: '2018',
			noSeries: false,
			series: [
			{
				seriesId: 'Cloverfield',
				seriesName: '科洛弗档案',
				seriesYear: '2008',
			},
			{
				seriesId: '10CloverfieldLane',
				seriesName: '科洛弗道10号',
				seriesYear: '2016',
			},
			{
				seriesId: 'TheCloverfieldParadox',
				seriesName: '科洛弗悖论',
				seriesYear: '2018',
			},
			],
			officialName: 'The Cloverfield Paradox',
			country: '美国',
			type: '科幻 / 悬疑 / 惊悚',
			director: '朱利叶斯·约拿',
			star: '古古·姆巴塔-劳 / 大卫·奥伊罗',
			note: '外星人入侵 屠杀 末日 逃生 人性 血腥',
			noBilibili: true,
			bilibiliUrl: '',
			noTencent: true,
			tencentUrl: '',
			noYouku: true,
			youkuUrl: '',
			noIqiyi: true,
			iqiyiUrl: '',
			noOther: false,
			otherUrl: 'https://www.halihali.tv/v/klfblklfda3/0-1.html',
			noDownload: true,
			downloadUrl: '',
		},
		],
	},
	methods: {
		scoreColor: function (item) {
			if (item.score >= 9) {
				return '#A020F0';
			}
			else if (item.score < 9 && item.score >= 8) {
				return '#0000FF';
			}
			else if (item.score < 8 && item.score >= 7) {
				return '#00FFFF';
			}
			else if (item.score < 7 && item.score >= 6) {
				return '#00FF00';
			}
			else if (item.score < 6 && item.score >= 5) {
				return '#FFFF00';
			}
			else if (item.score < 5 && item.score >= 4) {
				return '#FFA500';
			}
			else {
				return '#FF0000';
			}
		},
	},
});